### ISSUE TITLE
三种特殊弹药包的图像以及其动画

### ISSUE THREAD

**Issue by Demonmasterlqx** [Great-Love-League/moonbit-game-program#23]

**Comment by luoji12103** [comment]
![高爆子弹包(High_explosive_cartridge_bag)](https://github.com/user-attachments/assets/06b6ee48-c1d8-4b57-bf15-dd0d56825ef9)
![高爆子弹包动画1(High_explosive_cartridge_bag_frame1)](https://github.com/user-attachments/assets/3ec79414-75d0-48cd-9fdf-fc07f54e19fd)
![双倍子弹包(Double_cartridge_bag)](https://github.com/user-attachments/assets/e678c34d-de77-4d44-8505-b5f266b714ce)
![血量回复包(HP_Recovery_Pack)](https://github.com/user-attachments/assets/077ec530-d714-4f7d-8cb2-0544bf5d9853)
![血量回复包动画1(HP_Recovery_Pack_frame1)](https://github.com/user-attachments/assets/613a806f-d989-4bea-9486-8cfe8c9bab1f)
![血量回复包动画2(HP_Recovery_Pack_frame2)](https://github.com/user-attachments/assets/3b762b6c-bc10-41c3-9014-134767620b09)
![双倍子弹包动画1(Double_cartridge_bag_frame1)](https://github.com/user-attachments/assets/c20d1eb6-5bb5-452c-b9cf-c45c3f692a6c)

**Comment by luoji12103** [comment]
[特殊道具包.zip](https://github.com/user-attachments/files/17395260/default.zip)

**Comment by luoji12103** [comment]
[特殊道具包.zip](https://github.com/user-attachments/files/17408784/default.zip)
添加激光子弹包

**Comment by luoji12103** [comment]
[修正_血量回复包(HP_Recovery_Pack).zip](https://github.com/user-attachments/files/17529430/_.HP_Recovery_Pack.zip)
