### ISSUE TITLE
子弹包 二期的不做

### ISSUE THREAD

**Issue by Demonmasterlqx** [Great-Love-League/moonbit-game-program#6]

**Comment by luoji12103** [comment]
![freecompress-Double_Bullet](https://github.com/user-attachments/assets/4e81a62c-3833-4f6c-90d6-9fe67918b77a)
![freecompress-Explosive_Bullet](https://github.com/user-attachments/assets/77be377b-cecb-41d0-8f8b-b85ddbc3b2c7)
![freecompress-Cure_Bag](https://github.com/user-attachments/assets/28fec3ff-7b2e-4967-a1e4-11261d6a2bad)

**Comment by luoji12103** [comment]
[props.zip](https://github.com/user-attachments/files/17270063/props.zip)
